 SELECT
    mv.bus_unit,
    mv.CROWN_AREA,
    mv.SITE_STATUS,
    mv.consent_summary,
    mv.CROWN_DISTRICT,
    mv.LATS,
    mv.LONGS,
    mv.PORTFOLIO,
    mv.SITE_CITY,
    mv.SITE_COUNTY,
    mv.SITE_STATE,
    mv.SITE_ZIP,
    mv.MARKETABLE,
    mv.FIBER_ON_SITE,
    mv.FIBER_PROVIDER,
    mv.IS_CCI_POWER_AVAILABLE,
    mv.IF_NO_CCI_POWER_IS_METER_AVAIL,
    mv.POWER_COMPANY,
    mv.AVAILABLE_TELCO_PROVIDER,
    mv.REVSHARE,
    mv.REVSHARE_SPLIT,
    mv.LANDLORD_NAME,
    mv.PRIMARY_PROPERTY_INTEREST,
    mv.TOWER_ONLY,
    mv.FLE,
    mv.LEASED_AREA_SQ_FT,
    mv.COMPOUND_SQ_FT,
    mv.COMPND_EXPAND,
    mv.SITE_STATUS,
    mv.AVAIL_GROUND_SPACE_COM,
    mv.ADD_LAND_OPTION,
    mv.OPTION_SQ_FT,
    mv.SUBLEASE_CONSENT_TYPE,
    mv.CONFIG_CHANGES_CONSENT_TYPE,
    mv.LOA_REQUIRED,
    mv.ZONING_JURISDICTION,
    mv.ZONING_COLLO_PROCESS_TYPE,
    mv.ZONING_ANT_ADD_PROCESS_TYPE,
    mv.ZONING_ANT_SWAP_PROCESS_TYPE,
    mv.ZONING_GROUND_PROCESS_TYPE,
    mv.PERMIT_JURISDICTION,
    mv.BP_COLLO_PERMIT_TYPE,
    mv.BP_ANT_ADD_PERMIT_TYPE,
    mv.BP_ANT_SWAP_PERMIT_TYPE,
    mv.BP_GROUND_PERMIT_TYPE,
    mv.TOWER_LIGHTED,
    mv.LARGEST_LENGTH,
    mv.LARGEST_WIDTH,
    si.site_flag,
    st.structure_type,
    st.stealth_tower_ind,
    st.structure_id,
    st.faa_apprv_hgt faa_approved_height,
    st.hgt_with_appurt tower_height_w_appurt,
    st.HGT_NO_APPURT TOWER_HEIGHT_WOUT_APPURT,
    st.ground_elev ground_elevation,
    st.faa_twr_lighting_req faa_lighting_requirement,
    str.MAN_LIFT_RQRD_IND man_lift_req,
    st.airport_dist NEAREST_AIRPORT_DISTANCE,
    mv.site_on_si_tracker,
    st.AM_DTNNG_EQPT_IND am_study_required,
    st.AIRPORT_DIST,
    st.FAA_STUDY_NUM FAA_STUDY_NUMBER,
    st.STEALTH_TOWER_TYPE_LKUP_CODE,
    mv.ABANDONED_EQUIPMENT_ON_TOWER,
    mv.SA_ON_FILE,
    mv.CURRENT_TOWER_CAPACITY,
    mv.MODIFICATION_EXPECTED,
    mv.CAN_IT_BE_IBM,
    mv.HIST_MIGRATORY_BIRD_ISSUES,
    mv.OPEN_BIRD_TICKET,
    mv.VALIDATED_FCC_REGISTRATION
 FROM
 gds.site_scrubbing_mv mv,
 isit_aim.site si,
 gds.structure st,
 isit_aim.us_structure str
 WHERE mv.bus_unit = si.bus_unit
 and si.site_flag = '1'
 and mv.bus_unit = st.bus_unit(+)
 and st.bus_unit = str.bus_unit
 and st.structure_id = str.structure_id
 and st.structure_id in ('A','B','C','D','E','F','G','C1','C2','C3','C4','C5','C6','C7','C8','C9','C10','C11','C12','C13','C14','C15','C16','C17','C18','C19','C20')
 and si.bus_unit in ()
 order by si.bus_unit, st.structure_id
 END
 -*-*-*****************************************
 -*-* Defining the SQL output for WebFocus
 -*TABLE FILE SQLOUT
 -*PRINT *
 -*-*
 -*-*ON TABLE HOLD AS SQLOUT2
 -*END
 -*-*
 -*-*
 -*-*
 -*-*
 -*-EXIT
 TABLE FILE SQLOUT
 PRINT *
 ON TABLE HOLD AS DATA1
 END
 DEFINE FILE DATA1
 -*STEALTH_TYPE_PLACEHOLDER/A50 = IF BUS_UNIT IS NOT MISSING THEN 'Placehold' ELSE '';
 -*STRUCTURE_ID_PLACEHOLDER/A50 = IF BUS_UNIT IS NOT MISSING THEN 'Placehold' ELSE '';
 STRUCTURE_TYPE_COL/A50 = 			IF STRUCTURE_TYPE EQ 'GUYED' OR 'MONOPOLE' OR 'SELF SUPPORT' THEN 'GREEN' ELSE
 IF STRUCTURE_TYPE EQ 'DAS' OR 'ROOFTOP' OR 'SINGLE USE' OR 'STEALTH' THEN 'RED' ELSE
 IF STRUCTURE_TYPE EQ 'COMPOUND' OR 'OTHER' OR 'UNCLASSIFIED' THEN 'YELLOW' ELSE '';
 STEALTH_TOWER_IND_COL/A50 =			IF STEALTH_TOWER_IND EQ 'Y' THEN 'RED' ELSE
 IF STEALTH_TOWER_IND NE 'Y' THEN 'GREEN' ELSE '';
 SITE_FLAG_COL/A50 =					IF SITE_FLAG EQ '1' THEN 'GREEN' ELSE
 IF SITE_FLAG NE '1' THEN 'RED' ELSE '';
 CURRENT_TOWER_CAPACITY_COL/A50 = 	IF CURRENT_TOWER_CAPACITY EQ 'N/A' THEN '' ELSE
 IF CURRENT_TOWER_CAPACITY LT '200' THEN 'GREEN' ELSE
 IF CURRENT_TOWER_CAPACITY GE '200' THEN 'RED' ELSE '';
 FAA_STUDY_NUMBER_COL/A50 = 			IF FAA_STUDY_NUMBER EQ '' THEN 'GREEN' ELSE
 IF FAA_STUDY_NUMBER NE '' THEN 'RED' ELSE '';
 OPEN_BIRD_TICKET_COL/A50 = 			IF OPEN_BIRD_TICKET EQ 'Y' THEN 'RED' ELSE
 IF OPEN_BIRD_TICKET NE 'Y' THEN 'GREEN' ELSE '';
 FLE_NUM/D20 = IF FLE IS NOT MISSING THEN FLE - 06/20/2021;
 FLE_COL/A50 = 						IF FLE_NUM LT 1825 THEN 'YELLOW' ELSE
 IF FLE_NUM GE 1825 THEN 'GREEN' ELSE '';
 PRIMARY_PROPERTY_INTEREST_COL/A50 =	IF PRIMARY_PROPERTY_INTEREST EQ 'MANAGED' THEN 'YELLOW' ELSE
 IF PRIMARY_PROPERTY_INTEREST GE 'LEASED' THEN 'GREEN' ELSE '';
 ZONING_COLLO_PROCESS_TYPE_COL/A50 =	IF ZONING_COLLO_PROCESS_TYPE EQ 'Admin' THEN 'YELLOW' ELSE
 IF ZONING_COLLO_PROCESS_TYPE EQ 'Concurrent' THEN 'YELLOW' ELSE
 IF ZONING_COLLO_PROCESS_TYPE EQ 'Full' THEN 'YELLOW' ELSE
 IF ZONING_COLLO_PROCESS_TYPE EQ 'No Zoning' THEN 'GREEN' ELSE
 IF ZONING_COLLO_PROCESS_TYPE EQ 'Over Counter' THEN 'YELLOW' ELSE '';
 ZONING_ANT_ADD_PROCESS_TYPE_COL/A50 = 	IF ZONING_ANT_ADD_PROCESS_TYPE EQ 'Admin' THEN 'YELLOW' ELSE
 IF ZONING_ANT_ADD_PROCESS_TYPE EQ 'Concurrent' THEN 'YELLOW' ELSE
 IF ZONING_ANT_ADD_PROCESS_TYPE EQ 'Full' THEN 'YELLOW' ELSE
 IF ZONING_ANT_ADD_PROCESS_TYPE EQ 'No Zoning' THEN 'GREEN' ELSE
 IF ZONING_ANT_ADD_PROCESS_TYPE EQ 'Over Counter' THEN 'YELLOW' ELSE '';
 ZONING_ANT_SWAP_PROCESS_TYPE_COL/A50 =	IF ZONING_ANT_SWAP_PROCESS_TYPE EQ 'Admin' THEN 'YELLOW' ELSE
 IF ZONING_ANT_SWAP_PROCESS_TYPE EQ 'Concurrent' THEN 'YELLOW' ELSE
 IF ZONING_ANT_SWAP_PROCESS_TYPE EQ 'Full' THEN 'YELLOW' ELSE
 IF ZONING_ANT_SWAP_PROCESS_TYPE EQ 'No Zoning' THEN 'GREEN' ELSE
 IF ZONING_ANT_SWAP_PROCESS_TYPE EQ 'Over Counter' THEN 'YELLOW' ELSE '';
 BP_COLLO_PERMIT_TYPE_COL/A50 =		IF BP_COLLO_PERMIT_TYPE EQ 'BP' THEN 'YELLOW' ELSE
 IF BP_COLLO_PERMIT_TYPE EQ 'BP + EP' THEN 'YELLOW' ELSE
 IF BP_COLLO_PERMIT_TYPE EQ 'Other' THEN 'YELLOW' ELSE
 IF BP_COLLO_PERMIT_TYPE EQ 'None' THEN 'GREEN' ELSE
 IF BP_COLLO_PERMIT_TYPE EQ 'BP + Other' THEN 'YELLOW' ELSE
 IF BP_COLLO_PERMIT_TYPE EQ 'Electrical' THEN 'YELLOW' ELSE '';
 BP_ANT_ADD_PERMIT_TYPE_COL/A50 =	IF BP_ANT_ADD_PERMIT_TYPE EQ 'BP' THEN 'YELLOW' ELSE
 IF BP_ANT_ADD_PERMIT_TYPE EQ 'BP + EP' THEN 'YELLOW' ELSE
 IF BP_ANT_ADD_PERMIT_TYPE EQ 'Other' THEN 'YELLOW' ELSE
 IF BP_ANT_ADD_PERMIT_TYPE EQ 'None' THEN 'GREEN' ELSE
 IF BP_ANT_ADD_PERMIT_TYPE EQ 'BP + Other' THEN 'YELLOW' ELSE
 IF BP_ANT_ADD_PERMIT_TYPE EQ 'Electrical' THEN 'YELLOW' ELSE '';
 BP_ANT_SWAP_PERMIT_TYPE_COL/A50 =	IF BP_ANT_SWAP_PERMIT_TYPE EQ 'BP' THEN 'YELLOW' ELSE
 IF BP_ANT_SWAP_PERMIT_TYPE EQ 'BP + EP' THEN 'YELLOW' ELSE
 IF BP_ANT_SWAP_PERMIT_TYPE EQ 'Other' THEN 'YELLOW' ELSE
 IF BP_ANT_SWAP_PERMIT_TYPE EQ 'None' THEN 'GREEN' ELSE
 IF BP_ANT_SWAP_PERMIT_TYPE EQ 'BP + Other' THEN 'YELLOW' ELSE
 IF BP_ANT_SWAP_PERMIT_TYPE EQ 'Electrical' THEN 'YELLOW' ELSE '';
 CONSENT_SUMMARY_COL/A50 =			IF BP_ANT_SWAP_PERMIT_TYPE EQ 'Consent - Deemed Approved' THEN 'YELLOW' ELSE
 IF BP_ANT_SWAP_PERMIT_TYPE EQ 'Consent - Intercompany' THEN 'GREEN' ELSE
 IF BP_ANT_SWAP_PERMIT_TYPE EQ 'Consent - No Standard Specified (NTBUW)' THEN 'YELLOW' ELSE
 IF BP_ANT_SWAP_PERMIT_TYPE EQ 'Consent - Non-Standard Requirement' THEN 'YELLOW' ELSE
 IF BP_ANT_SWAP_PERMIT_TYPE EQ 'Consent  NTBUW' THEN 'YELLOW' ELSE
 IF BP_ANT_SWAP_PERMIT_TYPE EQ 'Consent - Sole Discretion' THEN 'RED' ELSE
 IF BP_ANT_SWAP_PERMIT_TYPE EQ 'No Consent or Notice Required' THEN 'GREEN' ELSE
 IF BP_ANT_SWAP_PERMIT_TYPE EQ 'No Consent or Notice Required - IC Blanket Agreement' THEN 'GREEN' ELSE
 IF BP_ANT_SWAP_PERMIT_TYPE EQ 'No Consent or Notice Required  Silent' THEN 'GREEN' ELSE
 IF BP_ANT_SWAP_PERMIT_TYPE EQ 'Notice' THEN 'YELLOW' ELSE '';

 SET LINES = 99999
 TABLE FILE DATA1
 PRINT
 STRUCTURE_TYPE_COL NOPRINT
 STEALTH_TOWER_IND_COL NOPRINT
 SITE_FLAG_COL NOPRINT
 CURRENT_TOWER_CAPACITY_COL NOPRINT
 FAA_STUDY_NUMBER_COL NOPRINT
 OPEN_BIRD_TICKET_COL NOPRINT
 FLE_COL NOPRINT
 FLE_NUM NOPRINT
 FLE NOPRINT
 PRIMARY_PROPERTY_INTEREST_COL NOPRINT
 ZONING_COLLO_PROCESS_TYPE_COL NOPRINT
 ZONING_ANT_ADD_PROCESS_TYPE_COL NOPRINT
 ZONING_ANT_SWAP_PROCESS_TYPE_COL NOPRINT
 BP_COLLO_PERMIT_TYPE_COL NOPRINT
 BP_ANT_ADD_PERMIT_TYPE_COL NOPRINT
 BP_ANT_SWAP_PERMIT_TYPE_COL NOPRINT
 CONSENT_SUMMARY_COL NOPRINT
 BUS_UNIT
 -*STRUCTURE_ID_PLACEHOLDER
 STRUCTURE_ID
 CROWN_AREA
 CROWN_DISTRICT
 LATS
 LONGS
 PORTFOLIO
 SITE_CITY
 SITE_COUNTY
 SITE_STATE
 SITE_ZIP
 SITE_FLAG
 STRUCTURE_TYPE
 STEALTH_TOWER_IND
 STEALTH_TOWER_TYPE_LKUP_CODE AS 'CDS_TYPE'
 FAA_APPROVED_HEIGHT
 TOWER_HEIGHT_W_APPURT
 TOWER_HEIGHT_WOUT_APPURT
 GROUND_ELEVATION
 MARKETABLE
 FAA_LIGHTING_REQUIREMENT
 FIBER_ON_SITE
 FIBER_PROVIDER
 IS_CCI_POWER_AVAILABLE
 IF_NO_CCI_POWER_IS_METER_AVAIL
 POWER_COMPANY
 AVAILABLE_TELCO_PROVIDER
 MAN_LIFT_REQ
 ABANDONED_EQUIPMENT_ON_TOWER
 SA_ON_FILE
 CURRENT_TOWER_CAPACITY
 SITE_ON_SI_TRACKER
 MODIFICATION_EXPECTED
 CAN_IT_BE_IBM
 REVSHARE
 REVSHARE_SPLIT
 LANDLORD_NAME
 CONSENT_SUMMARY
 PRIMARY_PROPERTY_INTEREST
 TOWER_ONLY
 FLE
 LEASED_AREA_SQ_FT
 COMPOUND_SQ_FT
 COMPND_EXPAND
 SITE_STATUS
 AVAIL_GROUND_SPACE_COM
 ADD_LAND_OPTION
 OPTION_SQ_FT
 SUBLEASE_CONSENT_TYPE
 CONFIG_CHANGES_CONSENT_TYPE
 LOA_REQUIRED
 ZONING_JURISDICTION
 ZONING_COLLO_PROCESS_TYPE
 ZONING_ANT_ADD_PROCESS_TYPE
 ZONING_ANT_SWAP_PROCESS_TYPE
 ZONING_GROUND_PROCESS_TYPE
 PERMIT_JURISDICTION
 BP_COLLO_PERMIT_TYPE
 BP_ANT_ADD_PERMIT_TYPE
 BP_ANT_SWAP_PERMIT_TYPE
 BP_GROUND_PERMIT_TYPE
 AM_STUDY_REQUIRED
 HIST_MIGRATORY_BIRD_ISSUES
 OPEN_BIRD_TICKET
 NEAREST_AIRPORT_DISTANCE
 TOWER_LIGHTED
 FAA_STUDY_NUMBER
 VALIDATED_FCC_REGISTRATION
 LARGEST_LENGTH
 LARGEST_WIDTH
 BY BUS_UNIT NOPRINT
 BY STRUCTURE_ID NOPRINT
 ON TABLE SET PAGE-NUM OFF
 ON TABLE SET BYDISPLAY ON
 ON TABLE NOTOTAL
 -*ON TABLE PCHOLD FORMAT EXL2K
 -*ON TABLE HOLD AS SCRUBDATA FORMAT ALPHA
 ON TABLE SET STYLE *
 $
 TYPE=REPORT,
 COLUMN=STRUCTURE_TYPE,
 BACKCOLOR=GREEN,
 COLOR=WHITE,
 WHEN =  STRUCTURE_TYPE_COL EQ 'GREEN',
 $
 TYPE=REPORT,
 COLUMN=STRUCTURE_TYPE,
 BACKCOLOR=RED,
 COLOR=WHITE,
 WHEN =  STRUCTURE_TYPE_COL EQ 'RED',
 $
 TYPE=REPORT,
 COLUMN=STRUCTURE_TYPE,
 BACKCOLOR=YELLOW,
 COLOR=BLACK,
 WHEN =  STRUCTURE_TYPE_COL EQ 'YELLOW',
 $
 TYPE=REPORT,
 COLUMN=STEALTH_TOWER_IND,
 BACKCOLOR=GREEN,
 COLOR=WHITE,
 WHEN =  STEALTH_TOWER_IND_COL EQ 'GREEN',
 $
 TYPE=REPORT,
 COLUMN=STEALTH_TOWER_IND,
 BACKCOLOR=RED,
 COLOR=WHITE,
 WHEN =  STEALTH_TOWER_IND_COL EQ 'RED',
 $
 TYPE=REPORT,
 COLUMN=SITE_FLAG,
 BACKCOLOR=GREEN,
 COLOR=WHITE,
 WHEN =  SITE_FLAG_COL EQ 'GREEN',
 $
 TYPE=REPORT,
 COLUMN=SITE_FLAG,
 BACKCOLOR=RED,
 COLOR=WHITE,
 WHEN =  SITE_FLAG_COL EQ 'RED',
 $
 TYPE=REPORT,
 COLUMN=CURRENT_TOWER_CAPACITY,
 BACKCOLOR=GREEN,
 COLOR=WHITE,
 WHEN =  CURRENT_TOWER_CAPACITY_COL EQ 'GREEN',
 $
 TYPE=REPORT,
 COLUMN=CURRENT_TOWER_CAPACITY,
 BACKCOLOR=RED,
 COLOR=WHITE,
 WHEN =  CURRENT_TOWER_CAPACITY_COL EQ 'RED',
 $
 TYPE=REPORT,
 COLUMN=FAA_STUDY_NUMBER,
 BACKCOLOR=GREEN,
 COLOR=WHITE,
 WHEN =  FAA_STUDY_NUMBER_COL EQ 'GREEN',
 $
 TYPE=REPORT,
 COLUMN=FAA_STUDY_NUMBER,
 BACKCOLOR=RED,
 COLOR=WHITE,
 WHEN =  FAA_STUDY_NUMBER_COL EQ 'RED',
 $
 TYPE=REPORT,
 COLUMN=OPEN_BIRD_TICKET,
 BACKCOLOR=GREEN,
 COLOR=WHITE,
 WHEN =  OPEN_BIRD_TICKET_COL EQ 'GREEN',
 $
 TYPE=REPORT,
 COLUMN=OPEN_BIRD_TICKET,
 BACKCOLOR=RED,
 COLOR=WHITE,
 WHEN =  OPEN_BIRD_TICKET_COL EQ 'RED',
 $
 TYPE=REPORT,
 COLUMN=FLE,
 BACKCOLOR=GREEN,
 COLOR=WHITE,
 WHEN =  FLE_COL EQ 'GREEN',
 $
 TYPE=REPORT,
 COLUMN=OPEN_BIRD_TICKET,
 BACKCOLOR=YELLOW,
 COLOR=BLACK,
 WHEN =  FLE_COL EQ 'YELLOW',
 $
 TYPE=REPORT,
 COLUMN=PRIMARY_PROPERTY_INTEREST,
 BACKCOLOR=GREEN,
 COLOR=WHITE,
 WHEN =  PRIMARY_PROPERTY_INTEREST_COL EQ 'GREEN',
 $
 TYPE=REPORT,
 COLUMN=PRIMARY_PROPERTY_INTEREST,
 BACKCOLOR=YELLOW,
 COLOR=BLACK,
 WHEN =  PRIMARY_PROPERTY_INTEREST_COL EQ 'YELLOW',
 $
 TYPE=REPORT,
 COLUMN=ZONING_COLLO_PROCESS_TYPE,
 BACKCOLOR=GREEN,
 COLOR=WHITE,
 WHEN =  ZONING_COLLO_PROCESS_TYPE_COL EQ 'GREEN',
 $
 TYPE=REPORT,
 COLUMN=ZONING_COLLO_PROCESS_TYPE,
 BACKCOLOR=YELLOW,
 COLOR=BLACK,
 WHEN =  ZONING_COLLO_PROCESS_TYPE_COL EQ 'YELLOW',
 $
 TYPE=REPORT,
 COLUMN=ZONING_ANT_ADD_PROCESS_TYPE,
 BACKCOLOR=GREEN,
 COLOR=WHITE,
 WHEN =  ZONING_ANT_ADD_PROCESS_TYPE_COL EQ 'GREEN',
 $
 TYPE=REPORT,
 COLUMN=ZONING_ANT_ADD_PROCESS_TYPE,
 BACKCOLOR=YELLOW,
 COLOR=BLACK,
 WHEN =  ZONING_ANT_ADD_PROCESS_TYPE_COL EQ 'YELLOW',
 $
 TYPE=REPORT,
 COLUMN=ZONING_ANT_SWAP_PROCESS_TYPE,
 BACKCOLOR=GREEN,
 COLOR=WHITE,
 WHEN =  ZONING_ANT_SWAP_PROCESS_TYPE_COL EQ 'GREEN',
 $
 TYPE=REPORT,
 COLUMN=ZONING_ANT_SWAP_PROCESS_TYPE,
 BACKCOLOR=YELLOW,
 COLOR=BLACK,
 WHEN =  ZONING_ANT_SWAP_PROCESS_TYPE_COL EQ 'YELLOW',
 $
 TYPE=REPORT,
 COLUMN=BP_COLLO_PERMIT_TYPE,
 BACKCOLOR=GREEN,
 COLOR=WHITE,
 WHEN =  BP_COLLO_PERMIT_TYPE_COL EQ 'GREEN',
 $
 TYPE=REPORT,
 COLUMN=BP_COLLO_PERMIT_TYPE,
 BACKCOLOR=YELLOW,
 COLOR=BLACK,
 WHEN =  BP_COLLO_PERMIT_TYPE_COL EQ 'YELLOW',
 $
 TYPE=REPORT,
 COLUMN=BP_ANT_ADD_PERMIT_TYPE,
 BACKCOLOR=GREEN,
 COLOR=WHITE,
 WHEN =  BP_ANT_ADD_PERMIT_TYPE_COL EQ 'GREEN',
 $
 TYPE=REPORT,
 COLUMN=BP_ANT_ADD_PERMIT_TYPE,
 BACKCOLOR=YELLOW,
 COLOR=BLACK,
 WHEN =  BP_ANT_ADD_PERMIT_TYPE_COL EQ 'YELLOW',
 $
 TYPE=REPORT,
 COLUMN=BP_ANT_SWAP_PERMIT_TYPE,
 BACKCOLOR=GREEN,
 COLOR=WHITE,
 WHEN =  BP_ANT_SWAP_PERMIT_TYPE_COL EQ 'GREEN',
 $
 TYPE=REPORT,
 COLUMN=BP_ANT_SWAP_PERMIT_TYPE,
 BACKCOLOR=YELLOW,
 COLOR=BLACK,
 WHEN =  BP_ANT_SWAP_PERMIT_TYPE_COL EQ 'YELLOW',
 $
 TYPE=REPORT,
 COLUMN=CONSENT_SUMMARY,
 BACKCOLOR=GREEN,
 COLOR=WHITE,
 WHEN =  CONSENT_SUMMARY_COL EQ 'GREEN',
 $
 TYPE=REPORT,
 COLUMN=CONSENT_SUMMARY,
 BACKCOLOR=RED,
 COLOR=WHITE,
 WHEN =  CONSENT_SUMMARY_COL EQ 'RED',
 $
 TYPE=REPORT,
 COLUMN=CONSENT_SUMMARY,
 BACKCOLOR=YELLOW,
 COLOR=BLACK,
 WHEN =  CONSENT_SUMMARY_COL EQ 'YELLOW',
 $
 ENDSTYLE
 END
 -EXIT
 (FOC1400) SQLCODE IS 936 (HEX: 000003A8)
 : ORA-00936: missing expression
 : Error context area: _unit in (["BUN"]) o
 L    (FOC1405) SQL PREPARE ERROR.
 0 ERROR AT OR NEAR LINE    143  IN PROCEDURE site_scrub_fike
 (FOC205) THE DESCRIPTION CANNOT BE FOUND FOR FILE NAMED: SQLOUT
 BYPASSING TO END OF COMMAND
 0 ERROR AT OR NEAR LINE    148  IN PROCEDURE site_scrub_fike
 (FOC205) THE DESCRIPTION CANNOT BE FOUND FOR FILE NAMED: DATA1
 0 ERROR AT OR NEAR LINE    238  IN PROCEDURE site_scrub_fike
 (FOC205) THE DESCRIPTION CANNOT BE FOUND FOR FILE NAMED: DATA1
 BYPASSING TO END OF COMMAND

