select
    mv.bus_unit,
    mv.crown_area,
    mv.site_status,
    mv.consent_summary,
    mv.crown_district,
    mv.lats,
    mv.longs,
    mv.portfolio,
    mv.site_city,
    mv.site_county,
    mv.site_state,
    mv.site_zip,
    mv.marketable,
    mv.fiber_on_site,
    mv.fiber_provider,
    mv.is_cci_power_available,
    mv.if_no_cci_power_is_meter_avail,
    mv.power_company,
    mv.available_telco_provider,
    mv.revshare,
    mv.revshare_split,
    mv.landlord_name,
    mv.primary_property_interest,
    mv.tower_only,
    mv.fle,
    mv.leased_area_sq_ft,
    mv.compound_sq_ft,
    mv.compnd_expand,
    mv.avail_ground_space_com,
    mv.add_land_option,
    mv.option_sq_ft,
    mv.sublease_consent_type,
    mv.config_changes_consent_type,
    mv.loa_required,
    mv.zoning_jurisdiction,
    mv.zoning_collo_process_type,
    mv.zoning_ant_add_process_type,
    mv.zoning_ant_swap_process_type,
    mv.zoning_ground_process_type,
    mv.permit_jurisdiction,
    mv.bp_collo_permit_type,
    mv.bp_ant_add_permit_type,
    mv.bp_ant_swap_permit_type,
    mv.bp_ground_permit_type,
    mv.tower_lighted,
    mv.largest_length,
    mv.stealth_tower_ind,
    mv.stealth_structure_type,
    mv.faa_study_number,
    mv.faa_approved_height,
    mv.structure_id,
    mv.ground_elevation,
    mv.faa_lighting_requirement,
    mv.man_lift_req,
    mv.nearest_airport_distance,
    mv.site_on_si_tracker,
    mv.am_study_required,
    mv.abandoned_equipment_on_tower,
    mv.sa_on_file,
    mv.current_tower_capacity,
    mv.modification_expected,
    mv.can_it_be_ibm,
    mv.hist_migratory_bird_issues,
    mv.open_bird_ticket,
    mv.validated_fcc_registration,
    st.s_structure_type,
    st.s_hgt_with_appurt,
    st.s_site_flag
from
    odw.gis_dw_private.private_cci_sites_scrubbing_vw mv

join

    odw.gis_dw_private.private_cci_sites_vw st on mv.bus_unit = st.s_bus_unit

where

    mv.structure_id in ('A','B','C','D','E','F','G','C1','C2','C3','C4','C5','C6','C7','C8','C9','C10','C11','C12','C13','C14','C15','C16','C17','C18','C19','C20')

order by mv.bus_unit, mv.structure_id