FW_FIELD_MAP = [
    ['fw_rank', 'Short'],
    ['candidate_type', 'Text'],
    ['id', 'Text'],
    ['cand_dist_km', 'Double'],
    ['long', 'Double'],
    ['lat', 'Double'],
    ['height', 'Short'],
    ['Clearance_Score', 'Text'],
    ['antenna', 'Text'],
    ['Speed', 'Short'],
    ['d_km', 'Double'],
    ['link_margin', 'Double'],
    ['Equipment', 'Text'],
    ['modulation', 'Text'],
    ['oxygen_attenuation_km', 'Double'],
    ['rain_attenuation_km', 'Double'],
    ['rain_attenuation_total', 'Double'],
    ['name', 'Text'],
    ['clli', 'Text'],
    ['street', 'Text'],
    ['city', 'Text'],
    ['state', 'Text'],
    ['structure', 'Text'],
    ['score', 'Double'],
    ['fcc_count','Long'],
    ['demand_1500m','Long'],
    ['demand_4000m','Long'],
    ['demand_8000m','Long'],
    ['crown_ae', 'Text'],
    ['revshare', 'Text'],
    ['s_hgt_no_appurt', 'Double'],
    ['open_levels', 'Text', 'open_levels',500],
    ['current_tower_capacity', 'Text'],
    ['last_sa_tia_code_revision', 'Text'],
    ['fiber_on_site', 'Text'],
    ['fiber_provider', 'Text'],
    ['is_cci_power_available', 'Text'],
    ['if_no_cci_power_is_meter_avail', 'Text'],
    ['power_company', 'Text'],
    ['active_apps_count_on_site', 'Double'],
    ['pt_id', 'Short'],
    ['poptier', 'Text'],
    ['site_county', 'Text'],
    ['TX_AGL', 'Short'],
    ['uid2', 'Text'],
    ['Fi_Dist', 'Double'],
    ['status','Text'],
    ['data_consistent','Text']
]