SELECT
mv.bus_unit,
mv.CROWN_AREA,
mv.SITE_STATUS,
mv.consent_summary,
mv.CROWN_DISTRICT,
mv.LATS,
mv.LONGS,
mv.PORTFOLIO,
mv.SITE_CITY,
mv.SITE_COUNTY,
mv.SITE_STATE,
mv.SITE_ZIP,
mv.MARKETABLE,
mv.FIBER_ON_SITE,
mv.FIBER_PROVIDER,
mv.IS_CCI_POWER_AVAILABLE,
mv.IF_NO_CCI_POWER_IS_METER_AVAIL,
mv.POWER_COMPANY,
mv.AVAILABLE_TELCO_PROVIDER,
mv.REVSHARE,
mv.REVSHARE_SPLIT,
mv.LANDLORD_NAME,
mv.PRIMARY_PROPERTY_INTEREST,
mv.TOWER_ONLY,
mv.FLE,
mv.LEASED_AREA_SQ_FT,
mv.COMPOUND_SQ_FT,
mv.COMPND_EXPAND,
mv.SITE_STATUS,
mv.AVAIL_GROUND_SPACE_COM,
mv.ADD_LAND_OPTION,
mv.OPTION_SQ_FT,
mv.SUBLEASE_CONSENT_TYPE,
mv.CONFIG_CHANGES_CONSENT_TYPE,
mv.LOA_REQUIRED,
mv.ZONING_JURISDICTION,
mv.ZONING_COLLO_PROCESS_TYPE,
mv.ZONING_ANT_ADD_PROCESS_TYPE,
mv.ZONING_ANT_SWAP_PROCESS_TYPE,
mv.ZONING_GROUND_PROCESS_TYPE,
mv.PERMIT_JURISDICTION,
mv.BP_COLLO_PERMIT_TYPE,
mv.BP_ANT_ADD_PERMIT_TYPE,
mv.BP_ANT_SWAP_PERMIT_TYPE,
mv.BP_GROUND_PERMIT_TYPE,
mv.TOWER_LIGHTED,
mv.LARGEST_LENGTH,
mv.LARGEST_WIDTH,
si.site_flag,
st.structure_type,
st.stealth_tower_ind,
st.structure_id,
st.faa_apprv_hgt faa_approved_height,
st.hgt_with_appurt tower_height_w_appurt,
st.HGT_NO_APPURT TOWER_HEIGHT_WOUT_APPURT,
st.ground_elev ground_elevation,
st.faa_twr_lighting_req faa_lighting_requirement,
str.MAN_LIFT_RQRD_IND man_lift_req,
st.airport_dist NEAREST_AIRPORT_DISTANCE,
mv.site_on_si_tracker,
st.AM_DTNNG_EQPT_IND am_study_required,
st.AIRPORT_DIST,
st.FAA_STUDY_NUM FAA_STUDY_NUMBER,
st.STEALTH_TOWER_TYPE_LKUP_CODE,
mv.ABANDONED_EQUIPMENT_ON_TOWER,
mv.SA_ON_FILE,
mv.CURRENT_TOWER_CAPACITY,
mv.MODIFICATION_EXPECTED,
mv.CAN_IT_BE_IBM,
mv.HIST_MIGRATORY_BIRD_ISSUES,
mv.OPEN_BIRD_TICKET,
mv.VALIDATED_FCC_REGISTRATION

FROM
odw.gis_dw_private.private_cci_sites_scrubbing_vw mv,
isit_aim.site si,
gds.structure st,
isit_aim.us_structure str

WHERE mv.bus_unit = si.bus_unit
and si.site_flag = '1'
and mv.bus_unit = st.bus_unit(+)
and st.bus_unit = str.bus_unit
and st.structure_id = str.structure_id
and st.structure_id in ('A','B','C','D','E','F','G','C1','C2','C3','C4','C5','C6','C7','C8','C9','C10','C11','C12','C13','C14','C15','C16','C17','C18','C19','C20')
and si.bus_unit in (["876502,876229"])
order by si.bus_unit, st.structure_id